baseurl = "https://www.cluboeno.com/"
title = "Cluboeno"
theme = "NederburgByLechaps"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
preserveTaxonomyNames = true
pagination.pagerSize = 20 #frontpage pagination
summaryLength = 5

[markup.goldmark.renderer]
unsafe= true # permet d'utiliser du HTML dans les articles markdown

[related]
  threshold = 80.0
  includeNewer = true
  toLower = false

  [[related.indices]]
  name = "tags"
  weight = 70.0

  [[related.indices]]
  name = "categories"
  weight = 20.0

  [[related.indices]]
  name = "writer"
  weight = 10.0

[outputs]
  home = ["HTML"]
  section = ["HTML", "json"]
  page = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"
  writer = "writer"

[params]
  #usepostimgfolder = true # Unmark to use post folder for images. Default is static folder.
  slogan = "L'oenologie pour tous"
  description = "Cluboeno, votre club oenologie en ligne. Des dégustations, des articles, des informations, tout ce que vous devez savoir si vous aimez l'univer du vin et des spiritueux." # meta description
  copyright = [
    "&copy; 2024 www.cluboeno.com",
    "L'alcool est à consommer avec modération...",
  ]
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "LeChaps"
  authorLink = "."
  avatar = "/img/lechaps_icone.jpg"
  bio = [
    "Amoureux du vin depuis toujours, LeChaps est le concepteur de ce site."
  ]

  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "contact@cluboeno.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Technique"
  url = "post/"
  weight = 1

  [[menu.main]]
  name = "Dégustation"
  url = "club/"
  weight = 2

  [[menu.main]]
  name = "Arômes"
  url = "/wheel"
  weight = 3

  [[menu.main]]
  name = "Présentation"
  url = "about/"
  weight = 4

  [[menu.main]]
  name = "Contact"
  url = "contact/"
  weight = 5

  [[menu.main]]
  name = "Recherche"
  url = "https://www.google.com/search?q=site%3Acluboeno.com"
  weight = 6





# this will also be in author bio if there is no writer.
  [params.social]
  facebook      = "https://www.facebook.com/lecluboeno"
  email         = "contact@cluboeno.com"
  twitter       = "https://twitter.com/club_oeno"
  instagram     = "https://www.instagram.com/club_oeno"
  github        = "https://github.com/lechaps/cluboeno"
  pinterest     = "https://www.pinterest.fr/lechaps03"

# Add a writer, then use it in the markdown front matter like this: writer = "the name of the writer"
  [params.writers]
    [params.writers."LeChaps"]
    link = "https://www.lechaps.com"
    email = "lechaps@cluboeno.com"
    avatar = "/img/lechaps_icone.jpg"
    bio = [
      "Avant de dire qu'un vin est mauvais, pensez à ceux qui l'ont fait et à ce qu'il vous a couté. Parce qu'au final, quoi qu'il arrive, on en boira toujours du plus mauvais !"
    ]
    facebook      = "https://www.facebook.com/TheChaps"
    twitter       = "https://www.twitter.com/lechaps"
    linkedin      = "https://www.linkedin.com/in/romainchapon"
    instagram     = "https://www.instagram.com/club_oeno"
    github        = "https://github.com/lechaps/cluboeno"
    pinterest     = "https://www.pinterest.fr/lechaps03"
    stackoverflow = ""

    [params.writers."Thomas"]
    link = ""
    email = ""
    avatar = "/img/thomas_icone.jpg"
    bio = [
      "Dans la vie, faut être curieux ! Signé un découvreur de belles émotions."
    ]
    facebook      = ""
    twitter       = ""
    linkedin      = ""
    instagram     = ""
    github        = ""
    pinterest     = ""
    stackoverflow = ""

    [params.writers."Philippe"]
    link = ""
    email = ""
    avatar = "/img/philippe_icone.jpg"
    bio = [
      "Un vin ? Allons jeune homme, vous pouvez faire mieux ! Que dis-je, un nectar, que dis-je une oeuvre d'art, un sommet !"
    ]
    facebook      = ""
    twitter       = ""
    linkedin      = ""
    instagram     = ""
    github        = ""
    pinterest     = ""
    stackoverflow = ""

    [params.writers."Vince"]
    link = ""
    email = ""
    avatar = "/img/vince_icone.jpg"
    bio = [
      "Un verre de vin c'est bon pour la santé, le reste de la bouteille c'est bon pour le moral. Suivez la prescription du Docteur."
    ]
    facebook      = ""
    twitter       = ""
    linkedin      = ""
    instagram     = ""
    github        = ""
    pinterest     = ""
    stackoverflow = ""

    [params.writers."Benoit"]
    link = ""
    email = ""
    avatar = "/img/benoit_icone.jpg"
    bio = [
      ""
    ]
    facebook      = ""
    twitter       = ""
    linkedin      = ""
    instagram     = ""
    github        = ""
    pinterest     = ""
    stackoverflow = ""

    [params.writers."Alain"]
    link = ""
    email = ""
    avatar = "/img/alain_icone.jpg"
    bio = [
      "Je suis heureux et amusé de faire partie d’un groupe d’amateurs éclairés et pointus pour apprécier et découvrir des appellations connues et moins connues, mais de faire vivre la vigne, avec tout le savoir-faire du vigneron à son origine."    ]
    facebook      = ""
    twitter       = ""
    linkedin      = ""
    instagram     = ""
    github        = ""
    pinterest     = ""
    stackoverflow = ""

    [params.writers."Christophe"]
    link = ""
    email = ""
    avatar = "/img/christophe_icone.jpg"
    bio = [
      "Un jour, je serai dans le club oeno. En attendant je bois du vin..."    ]
    facebook      = ""
    twitter       = ""
    linkedin      = ""
    instagram     = ""
    github        = ""
    pinterest     = ""
    stackoverflow = ""
